version: '3.8'
services:
  dev_container:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    container_name: movie_recommendation_dev
    volumes:
      - .:/workspace
    network_mode: service:db
    
  db:
    image: postgres:14
    container_name: movie_recommendation_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: