version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_recommendation_dev
    command : ["sleep", "infinity"]
    volumes:
      - ..:/workspace
    networks:
      - backend
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:14
    container_name: movie_recommendation_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
